/-
Named axioms for [hyp]-tagged source claims (Bucket C).
Downstream theorems in Conditional.lean are proved relative to these axioms.
Source: antigravity_secondorder_main_v47_AFLB.tex
-/

namespace AflbLean.Hypotheses

/--
**Shared Basis Hypothesis.**
The A(R)-space operators are generated by the same topological operation basis
{G, L} as the physical state space P-space.
Declared [hyp]; defeater: a topological change in A(R)-space without G/L representation.
Source: main prop:shared-basis.
-/
axiom sharedBasis : Prop
axiom sharedBasis_holds : sharedBasis

/--
**Pachner Typed Metric Axiom.**
The typed G/L operations realize elementary bistellar moves and are complete for PL topology.
Declared [hyp]; defeater: an edge whose simplicial realization is not a G/L composition.
Source: main def:operation-basis, prop:smallest-scale.
-/
axiom pachnerTyped : Prop
axiom pachnerTyped_holds : pachnerTyped

/--
**Sync Residue Axiom.**
The synchronization residue ρ_{G/L}^{M,Q}(δ) is a well-defined relative class.
Declared [hyp]; presupposes the typed-bridge formalism.
Source: main prop:sync-residue.
-/
axiom syncResidueWellDefined : Prop
axiom syncResidueWellDefined_holds : syncResidueWellDefined

end AflbLean.Hypotheses
