/-
Named axioms for [hyp]-tagged source claims (Bucket C), legacy registration-
theory layer retained unchanged from the v47 build (the corresponding labels
are unchanged in v50). These are distinct from the new physics-determination
posits in Posits.lean.
Downstream theorems in Conditional.lean are proved relative to these axioms.
Source: antigravity_secondorder_main_v50_AFLB.tex
-/

namespace AflbLean.Legacy.Hypotheses

/--
**Shared Basis Hypothesis.**
The A(R)-space operators are generated by the same topological operation basis
{G, L} as the physical state space P-space.
Declared [hyp]; defeater: a topological change in A(R)-space without G/L representation.
Source: main prop:shared-basis (v50 line 335).
-/
axiom sharedBasis : Prop
axiom sharedBasis_holds : sharedBasis

/--
**Pachner Typed Metric Axiom.**
The typed G/L operations realize elementary bistellar moves and are complete for PL topology.
Declared [hyp]; defeater: an edge whose simplicial realization is not a G/L composition.
Source: main def:operation-basis (v50 line 256), prop:smallest-scale (v50 line 265).
-/
axiom pachnerTyped : Prop
axiom pachnerTyped_holds : pachnerTyped

/--
**Sync Residue Axiom.**
The synchronization residue ρ_{G/L}^{M,Q}(δ) is a well-defined relative class.
Declared [hyp]; presupposes the typed-bridge formalism.
Source: main prop:sync-residue (v50 line 386).
-/
axiom syncResidueWellDefined : Prop
axiom syncResidueWellDefined_holds : syncResidueWellDefined

end AflbLean.Legacy.Hypotheses
